#Player Lookup Config

#Disable Info: Say i disabled gamemode then it wouldn't show up when i do /plookup <name>
Flying:
Op: true
Whitelisted: true
Dead: true
Sleeping: true
Sneaking: true
Sprinting: true
Gamemode: true
Ip: true #Override the permission.

#If this is true then the above options will work on console
DisabledConsole: false